module.exports = {
  apps: [
    {
      name: "intia-back",
      script: "back/server.js",
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      env_development: {
        NODE_ENV: "development",
        JWT_SECRET: "mumuok",
        SWAGGER_USERNAME: "thorlex_admin",
        SWAGGER_PASSWORD: "anchor2024!",
        SWAGGER_KEY: "anchor2024!",
        PROXY: "http://localhost",
        PROXY_OTHER: "https://signalcam.onrender.com",
        PORT: 4000,
        CORS_ORIGINS: "*",
        COMPRESSION_LEVEL: 6,
        RATE_LIMIT_WINDOW_MS: 900000,
        RATE_LIMIT_MAX_REQUESTS: 100,
        EVENT_LOOP_DELAY_THRESHOLD_MS: 100,
        GC_INTERVAL_MS: 30000,
        MONGO_MAX_POOL_SIZE: 10,
        MONGO_URI:
          "mongodb+srv://blex:RLTHQ7cqh9VbtLn0@cluster0.qibjzlv.mongodb.net/",
        MONGO_POOL_SIZE: 5,
        PING_PASSWORD: "admin123taskify",
        EMAIL_PORT: 4007,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_PORT: 587,
        SMTP_USER: "beyasbekono@gmail.com",
        SMTP_PASS: "xdvg ysca pdcr sbrr",
        EMAIL_FROM: "noreply@taskify.local",
      },
    },
  ],
};
